drop table LOTTONUM;
drop table LTIME;
drop table SECTION;


CREATE TABLE LOTTONUM (
  LOTTONUMBER NUMBER(5) NOT NULL ,
  COUNT NUMBER(5) ,
  CONSTRAINT LOTTONUM_NUMBER_PK PRIMARY KEY(LOTTONUMBER)
);

CREATE TABLE LTIME (
  idLTIME NUMBER(5)  NOT NULL ,
  WINNUM NUMBER(5) ,
  BOUNS NUMBER(5)  ,
  PRIMARY KEY(idLTIME)
);

CREATE TABLE SECTION (
  SECTIONID NUMBER(5)  NOT NULL ,
  SHOWNUM NUMBER(5) ,
  PRIMARY KEY(SECTIONID)
);

INSERT INTO LOTTONUM VALUES(1, 110);
INSERT INTO LOTTONUM VALUES(2, 110);
INSERT INTO LOTTONUM VALUES(3, 110);
INSERT INTO LOTTONUM VALUES(4, 110);
INSERT INTO LOTTONUM VALUES(5, 110);
INSERT INTO LOTTONUM VALUES(6, 110);

commit;


