DROP table "NUMERAL_STATS";

CREATE table "NUMERAL_STATS" (
    "NUMBER_ID"         NUMBER NOT NULL,
    "NUMERAL_FREQUENCY" NUMBER,
    "TURN_FK"           NUMBER,
    "UNIT_ID_FK"        VARCHAR2(30),
    constraint  "NUMERAL_STATS_PK" primary key ("NUMBER_ID")
);


ALTER TABLE "NUMERAL_STATS" ADD CONSTRAINT "NUMERAL_STATS_FK" 
FOREIGN KEY ("TURN_FK")
REFERENCES "TOTAL_RESULT" ("TURN");


ALTER TABLE "NUMERAL_STATS" ADD CONSTRAINT "NUMERAL_STATS_FK2" 
FOREIGN KEY ("UNIT_ID_FK")
REFERENCES "UNIT_STATS" ("UNIT_ID");




commit;