DROP table "UNIT_PATTERN";

CREATE table "UNIT_PATTERN" (
    "PATTERN_ID"        NUMBER NOT NULL,
    "UNIT_NUMBER"       NUMBER,
    "PATTERN"    		VARCHAR2(30),
    "PATTERN_FREQUENCY" NUMBER,
    constraint  "UNIT_PATTERN_PK" primary key ("PATTERN_ID")
);
    
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (1 , 5, '[1, 1, 1, 1, 2]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (2 , 4, '[0, 1, 1, 2, 2]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (3 , 4, '[0, 1, 1, 1, 3]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (4 , 3, '[0, 0, 1, 1, 4]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (5 , 3, '[0, 0, 1, 2, 3]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (6 , 2, '[0, 0, 0, 1, 5]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (7 , 3, '[0, 0, 2, 2, 2]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (8 , 2, '[0, 0, 0, 2, 4]', 0);
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN, PATTERN_FREQUENCY) VALUES (9 , 2, '[0, 0, 0, 3, 3]', 0);

commit;