DROP table "UNIT_STATS";

CREATE table "UNIT_STATS" (
    "UNIT_ID"        VARCHAR2(30) NOT NULL,
    "UNIT_NUMBER"    NUMBER,
    "UNIT_FREQUENCY" NUMBER,
    constraint  "UNIT_STATS_PK" primary key ("UNIT_ID")
    );
    
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_NUMBER) VALUES ('A',9);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_NUMBER) VALUES ('B',10);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_NUMBER) VALUES ('C',10);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_NUMBER) VALUES ('D',10);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_NUMBER) VALUES ('E',6);


commit;