DROP table "UNIT_PATTERN";

CREATE table "UNIT_PATTERN" (
    "PATTERN_ID"        NUMBER NOT NULL,
    "UNIT_NUMBER"       NUMBER,
    "PATTERN"    		VARCHAR2(30),
    "PATTERN_FREQUENCY" NUMBER,
    constraint  "UNIT_PATTERN_PK" primary key ("PATTERN_ID")
);
    
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (1 , 6, '1/1/1/1/1/1/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (2 , 5, '1/1/1/1/2/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (3 , 4, '1/1/2/2/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (4 , 4, '1/1/1/3/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (5 , 3, '1/1/4/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (6 , 3, '1/2/3/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (7 , 2, '1/5/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (8 , 3, '2/2/2/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (9 , 2, '2/4/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (10, 2, '3/3/');
INSERT INTO UNIT_PATTERN (PATTERN_ID, UNIT_NUMBER , PATTERN) VALUES (11, 1, '6/');

commit;