DROP table "UNIT_STATS";

CREATE table "UNIT_STATS" (
    "UNIT_ID"        VARCHAR2(30) NOT NULL,
    "UNIT_RANGE"    NUMBER,
    "UNIT_FREQUENCY" NUMBER,
    constraint  "UNIT_STATS_PK" primary key ("UNIT_ID")
);
    
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_RANGE, UNIT_FREQUENCY) VALUES ('A',9, 912);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_RANGE, UNIT_FREQUENCY) VALUES ('B',10, 1002);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_RANGE, UNIT_FREQUENCY) VALUES ('C',10, 985);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_RANGE, UNIT_FREQUENCY) VALUES ('D',10, 1000);
INSERT INTO UNIT_STATS (UNIT_ID, UNIT_RANGE, UNIT_FREQUENCY) VALUES ('E',6, 595);

commit;